### ISSUE TITLE
FrameDecoder returns EOF for any input < 4 bytes

### ISSUE THREAD

**Issue by arthurprs** [BurntSushi/rust-snappy#42]
FrameDecoder returns EOF it it can't get a full block header (4 bytes) from the reader, so any input < 4 bytes returns EOF. I'm not sure if that's intended or not.

**Comment by BurntSushi** [comment]
Probably not. Sounds like a bug. I'm not sure when I'll have a chance to work on fixing this though. Patches welcome.
